"""scope student identities to their exam

Re-keys student_identities from a global primary key on pseudonym_hmac to a
composite (pseudonym_hmac, exam_id). The hmac has always been documented as a
per-exam value (docs/api_reference.md, docs/DPA_template.md) and the client-side
store already keys students by (pseudonymId, examId); the global server key was
the outlier. It made a pupil's identity unusable in a second exam, which blocked
importing a .bgproj workspace into another account on the same server.

scan_submissions references the identity, so its single-column foreign key is
replaced by a two-column one. That is a strengthening: the database now enforces
that a submission may only reference an identity registered under its own exam,
a rule previously checked in application code.

Revision ID: 0013_scope_identity_to_exam
Revises: 0012_pwd_reset_remove_invites
Create Date: 2026-08-18
"""
from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "0013_scope_identity_to_exam"
down_revision = "0012_pwd_reset_remove_invites"
branch_labels = None
depends_on = None

# Auto-generated by PostgreSQL for the unnamed constraints in 0001_initial.
_OLD_FK = "scan_submissions_pseudonym_hmac_fkey"
_PK = "student_identities_pkey"
_NEW_FK = "scan_submissions_identity_fkey"


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # SQLite cannot alter a primary key in place. The test suite builds its
        # schema from the models via metadata.create_all, so it already gets the
        # composite key without this migration.
        return

    # 1. Release the dependent foreign key before touching the primary key.
    op.execute(f"ALTER TABLE scan_submissions DROP CONSTRAINT IF EXISTS {_OLD_FK}")

    # 2. Swap the primary key. exam_id is already NOT NULL, so it is eligible.
    op.execute(f"ALTER TABLE student_identities DROP CONSTRAINT IF EXISTS {_PK}")
    op.execute(
        f"ALTER TABLE student_identities ADD CONSTRAINT {_PK} "
        "PRIMARY KEY (pseudonym_hmac, exam_id)"
    )

    # 3. Recreate the reference across both columns.
    op.execute(
        f"ALTER TABLE scan_submissions ADD CONSTRAINT {_NEW_FK} "
        "FOREIGN KEY (pseudonym_hmac, exam_id) "
        "REFERENCES student_identities (pseudonym_hmac, exam_id) ON DELETE CASCADE"
    )

    # 4. The composite unique index from 0001_initial is now redundant with the
    # primary key. It was already dropped in b05e912c399b, so this is defensive.
    op.execute("DROP INDEX IF EXISTS uq_student_identities_hmac_exam")


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # Reverting requires the hmac to be globally unique again. Rows that only
    # coexist under the composite key would violate the restored primary key, so
    # fail loudly rather than deleting a pupil's identity to make room.
    duplicates = bind.exec_driver_sql(
        "SELECT COUNT(*) FROM ("
        "  SELECT pseudonym_hmac FROM student_identities"
        "  GROUP BY pseudonym_hmac HAVING COUNT(*) > 1"
        ") AS d"
    ).scalar()
    if duplicates:
        raise RuntimeError(
            f"Cannot downgrade: {duplicates} pseudonym_hmac value(s) appear in more than "
            "one exam. Restoring the global primary key would require deleting student "
            "identities. Resolve these rows manually first."
        )

    op.execute(f"ALTER TABLE scan_submissions DROP CONSTRAINT IF EXISTS {_NEW_FK}")

    op.execute(f"ALTER TABLE student_identities DROP CONSTRAINT IF EXISTS {_PK}")
    op.execute(
        f"ALTER TABLE student_identities ADD CONSTRAINT {_PK} PRIMARY KEY (pseudonym_hmac)"
    )

    op.execute(
        f"ALTER TABLE scan_submissions ADD CONSTRAINT {_OLD_FK} "
        "FOREIGN KEY (pseudonym_hmac) "
        "REFERENCES student_identities (pseudonym_hmac) ON DELETE CASCADE"
    )
